### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by KaTolyk** [KaTolyk/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by amkalenyk** [comment]
- I'm the most succwssful person ever to run for the presidency, by far. Nobody's ever been mire successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney - I have a Guccs store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest - and you all know it! Please don't feel so stupid or insecure, it's not your fault.

**Comment by KaTolyk** [comment]
Thanks a lot
