### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by KaTolyk** [KaTolyk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by amkalenyk** [comment]
https://www.fb.com/DonaldTrump
https://www.whitehouse.gov/people/donald-j-trump/
https://twitter.com/realDonaldTrump
https://www.instagram.com/realDonaldTrump/
