### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by KaTolyk** [KaTolyk/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by amkalenyk** [comment]
[https://www.scmp.com/news/world/united-states-canada/article/3106561/donald-trump-biography-facts-wealth-health-and]

**Personality**
Trump is known for his abrasive style and has a habit – and seemingly enjoys – insulting people in public.
“He’s psychologically terrified by weakness,” said Peter Trumbore, a professor of political science at Oakland University in Michigan.
Trump’s attraction to power was on display long before he won the White House on a promise to “make America great again”.
**Lifestyle, diet and health**
It’s no secret Trump enjoys junk food. According to an insider’s account of his 2016 presidential bid, Trump’s preferred order at McDonald’s was two Big Macs, two Filet-O-Fishes and a chocolate shake.
**Marriages, children and other relationships**
Trump has been married three times: first to Ivana Trump (1977-1992) and they have three children, Donald Jnr, Eric and Ivanka. The couple split amid reports of infidelity on Trump’s part.

**Business ventures**
In the early 1980s, when Donald Trump cut the ribbon to Trump Tower and reopened Central Park’s beloved skating rink, the business magnate appeared the quintessential poster boy of the revival of a New York City plagued by financial crisis and crime.
He would dabble in hotels, casinos, an airline, steaks, even a “university”. Trump forged an image of success that even several bankruptcies could not falter.
He was a regular of Manhattan’s elite nightlife scene as well as the city’s tabloids. His hit television show The Apprentice took the myth of Trump national, making him a household name boasting of riches and clout, an unshakeable broker of deals.
Today, the Trump name is plastered on buildings in several countries, including golf clubs and resorts in Scotland and the United States.

**Fame and entertainment**
Trump was a celebrity before he became president, and hosted The Apprentice and The Celebrity Apprentice for 14 seasons, overseeing contestants competing in business challenges before deciding which ones to fire. And long before The Apprentice, the businessman was a regular fixture in the pages of New York’s daily newspapers, which covered his fights with other property developers and celebrities like Rosie O’Donnell.

**Wealth and debt**
Fortune magazine estimated Trump’s wealth as US$2.5 billion in September, but the magazine said the coronavirus pandemic had cost him US$600 million in 2020 as both the value of his office space and guest traffic to his hotels have fallen.

**Comment by KaTolyk** [comment]
very well
